contact_links:
  - name: Нарушение безопасности
    url: https://discord.gg/MwDDf6t
    about: По поводу серьёзных эксплойтов и уязвимостей необходимо писать @PJB3005. (PJB#3482 в Дискорде).
  - name: Запросить фичу
    url: https://hackmd.io/@ss14/docs
    about: В случае если фича связана с игрой в принципе, писать в [дискорд сервер апстрим](https://discord.gg/ZBFGnb3) в ином случае писать в [наш дискорд сервер](https://discord.gg/8HV9qcrBNR).
